language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  # NPM_TOKEN
  - secure: "hBo2Mi5LEnqjLUBElywrmySCiI+zZrnJfkFz8dmoNN+4H7YUtJVvKIa0QvQznLd4N8zGWFo86ki05aguTRQt3XFEWQGJy2NbEapBbqNZ3XHjIolJdMfEznAUMZx43G+fxSU8Tw57InmlTInOCI34Yse8Ixfyk3UnJSTtfXqEFGny8ZPEI8R7xV0fRtwIsgh0vJJCn3hBg81bTfT7ruXFsup0QyXxQEtnqFhmFBfP26gtiZmpsGE1EKzarg73ipLdI7FEq/nKuzxG/m+8WID8uSEobdCJHhgPbUpFrEq6ouCybWW3ZHUHwO3ajFbkJ4uL0NNpv7DI/pOwxjsXYx06etyHjWcqfpwsjGd6rPoLXpoF0TyuWx6xL3jQ9VN1vx8fzNR+G3UWstwiUNfCjgwhl1GNbpNKSOLDAeQ4yI4stvyhTzkmyE1Ji4JLOIYtdWP3gUUSyu3tWtY8UXTjsl5EtrKOw9z1IlYbaVNxtNXX1zBIDkw5PGtZZ3uxVakyhqyShIVmiSpwc/to3wvFgZ6dpqYKoG7sLGx1aw51TPWQmAjkFM/f0QGaW0JwbcmFK1uM91+KwmRTBds2j/Ytvs/aA3P86uoPrkVQc7H1Vft6GW400+iKoY9kSHPJPIsaW0P/WGd86FSZab5Nmm+hqy5mLjzVzd0UTwGy+/0CS3IZSBY="


install:
- npm install --progress=false

script:
- true

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/prepack-publish
