language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  # NPM_TOKEN
  - secure: "B+gJ+HQCOzEehl0bh8jfmpnhVSJgQkRE/XOjJCtl9of4RH2chfXvqHw1SIvX8vh52QEzNm+wcHJP6exZ5FvA7fBpWaC9MG5/CH9xal2/wVfyYfxTL6e5FPaLK1UmF44kxCquwvK8QV8DuIANh9sTfLKA3WFJdtEivZsWC+7nae2tpds+RF7TD8KYRc4qlEC5gSS9hSO/utBqYgRHUt9+YfLBPsk66Yldo04R69HaK6NuPW4rtTyg74Ri/zfB7+VY/DlHk/pQ3mFEYLdx2vXLu4osrzzZMm03NXVdP1Rxsde01yk6wnlPDuluMdr0KQZkV2C/6nVOTeiKfi7OwmuhNs2prUMfxcUAHfrj6fuJiBhBDrYsnFtI2u4WQUNcW9wQjmo0lSo6BaOVHivL+ptpJkFBfReqCSrgxpMNGPfPcoYCLLGIUOgrGOC0nP+nM8tpK2bMGkX9ySDo5c8d0UWgv7LWOte51Eq47kCc7W5Oplk5qYx8VraoREdqFAcymNyB3kjtzfPPBrYN40TnFQOAPTHQWyCrLwZXfsGzFL+gYTCebHsg22K45ABuwUfb0jPuG5pJSStIqO3zDzZEnv2IE+gMVryJEvTlc98NfExc/no0IQ69WsvXk1tSh7n2+JXKb+g6sY/j4GYvq/T8qdASuTKxTlMH42GFqOaKy3vhPG0="


install:
- npm install --progress=false

script:
- true

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/prepack-publish
